package notificationpartmsgpack

var NotificationPartTitle = NewStringPart("title")
var NotificationPartSummary = NewStringPart("summary")
var NotificationPartText = NewStringPart("text")
var NotificationPartHtml = NewStringPart("html")
var NotificationPartAttachment = NewBinaryPart("attachment")
var NotificationPartPicture = NewBinaryPart("picture")
var NotificationPartURL = NewStringPart("url")
var NotificationPartAttachmentURL = NewStringPart("attachmenturl")
var NotificationPartPictureURL = NewStringPart("pictureurl")

var NotificationPartTitleList = NewStringListPart("titlelist")
var NotificationPartSummaryList = NewStringListPart("summarylist")
var NotificationPartTextList = NewStringListPart("textlist")
var NotificationPartHtmlList = NewStringListPart("htmllist")
var NotificationPartAttachmentList = NewBinaryListPart("attachmentlist")
var NotificationPartPictureList = NewBinaryListPart("picturelist")
var NotificationPartAttachmentURLList = NewStringListPart("attachmenturllist")
var NotificationPartPictureURLList = NewStringListPart("pictureurllist")
var NotificationPartURLList = NewStringListPart("urllist")

var NotificationPartTitleMap = NewStringMapPart("titlemap")
var NotificationPartSummaryMap = NewStringMapPart("summarymap")
var NotificationPartTextMap = NewStringMapPart("textmap")
var NotificationPartHtmlMap = NewStringMapPart("htmlmap")
var NotificationPartAttachmentMap = NewBinaryMapPart("attachmentmap")
var NotificationPartPictureMap = NewBinaryMapPart("picturemap")
var NotificationPartAttachmentURLMap = NewStringMapPart("attachmenturlmap")
var NotificationPartPictureURLMAp = NewStringMapPart("pictureurlmap")
var NotificationPartURLMap = NewStringMapPart("urlmap")
