package messagepartmsgpack

var MessagePartTitle = NewStringPart("title")
var MessagePartSummary = NewStringPart("summary")
var MessagePartText = NewStringPart("text")
var MessagePartHtml = NewStringPart("html")
var MessagePartAttachment = NewBinaryPart("attachment")
var MessagePartPicture = NewBinaryPart("picture")
var MessagePartURL = NewStringPart("url")
var MessagePartAttachmentURL = NewStringPart("attachmenturl")
var MessagePartPictureURL = NewStringPart("pictureurl")

var MessagePartTitleList = NewStringListPart("titlelist")
var MessagePartSummaryList = NewStringListPart("summarylist")
var MessagePartTextList = NewStringListPart("textlist")
var MessagePartHtmlList = NewStringListPart("htmllist")
var MessagePartAttachmentList = NewBinaryListPart("attachmentlist")
var MessagePartPictureList = NewBinaryListPart("picturelist")
var MessagePartAttachmentURLList = NewStringListPart("attachmenturllist")
var MessagePartPictureURLList = NewStringListPart("pictureurllist")
var MessagePartURLList = NewStringListPart("urllist")

var MessagePartTitleMap = NewStringMapPart("titlemap")
var MessagePartSummaryMap = NewStringMapPart("summarymap")
var MessagePartTextMap = NewStringMapPart("textmap")
var MessagePartHtmlMap = NewStringMapPart("htmlmap")
var MessagePartAttachmentMap = NewBinaryMapPart("attachmentmap")
var MessagePartPictureMap = NewBinaryMapPart("picturemap")
var MessagePartAttachmentURLMap = NewStringMapPart("attachmenturlmap")
var MessagePartPictureURLMAp = NewStringMapPart("pictureurlmap")
var MessagePartURLMap = NewStringMapPart("urlmap")
